language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # - "3.7-dev"
  # - "pypy"
  # - "pypy3" # TODO: pkg_config issues

# command to install dependencies
install:
  - "pip install -r requirements.txt"

# command to run the dependencies
script:
  - "pytest tests"

# command to run tests
# jobs:
#   include:
#     - stage: "General tests"
#       python: "3.6"
#       script: "pytest"